services:

  mysql:
    image: mysql:8.4

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    container_name: zentra-mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: Ajiang123,.
      MYSQL_DATABASE: zentra

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.4

    container_name: zentra-redis

    restart: unless-stopped

    ports:
      - "6380:6379"

    volumes:
      - redis_data:/data

  kafka:
    image: apache/kafka:4.3.1

    container_name: zentra-kafka

    restart: unless-stopped

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_NUM_PARTITIONS: 3

    volumes:
      - kafka_data:/var/lib/kafka/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  zentra-server:
    image: zentra-server:1.0

    container_name: zentra-server

    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
      kafka:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: prod

volumes:
  mysql_data:
  redis_data:
  kafka_data: