server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zentra?useSSL=false&serverTimezone=UTC
    username: root
    password: Ajiang123,.

  jackson:
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:mapper/*.xml